import {execFileSync} from 'child_process';
import fs from 'fs';
import glob from 'glob';

const urls = `
http://abehiroshi.la.coocan.jp/
http://best-hashtags.com/
http://brasilista.blogspot.com/2017/08/maiores-pepitas-de-ouro-encontradas-no.html?m=0
http://c98540qo.beget.tech/
http://centrallibrary.cit.ac.in/
http://exocolonist.com/
http://kuafor.me/
http://melodic-class.glitch.me/debugger.html
http://mobiledtp.charislms.com/login.php
http://nobisnet.dk/kea/10_exam/karen_copenhagen/index.html
http://promotiespullen.web2printsoftware.nl/
http://staging.getmecab.com/
http://themonsite.com/
http://universovigil.com/
http://wamatex.pl/
http://www.asrar-e-deen.com/
http://www.bewoksushi.com/index.html
http://www.pompifresh.com/hemocalm/
http://www.promotiespullen.com/
http://www.ucarinc.com/
http://yargs.js.org/
http://yveschaput.com/
https://7up.in/
https://academy.elice.io/
https://activecorp.com.br/
https://agencia.pw/
https://agentur22.de/
https://aimementoring.com/
https://akash-manna.bitbucket.io/
https://akkikhambhata.wordpress.com/tag/jquery-get-element-value-from-ul-li/
https://alexandrammr.github.io/blog/10-things-I-love-about-Romania/
https://allcorp2.aspro-demo.ru/
https://alrowad.sa/
https://altbalajifire.firebaseapp.com/
https://amradelata.github.io/
https://angiewoodcreations.com/
https://animal-noises-d0f7b.firebaseapp.com/index.html
https://aphome.ru/
https://app.ft.com/myft/feed
https://app.starbucks.com/menu
https://archiveleeds.co.uk/
https://babyfairytale.com/home
https://bar.utoronto.ca/~asullivan/RNA-Browser/
https://bargainairticket.com/
https://belajarpwa-4k93wli64.now.sh/
https://bestepraxistipps.de/wohnungsbesichtigung-absagen/
https://bg.eurostrah.com/
https://biservis.com.tr/
https://bitbucket.org/
https://bluealba.com/
https://brave.com/
https://browser.sentry-cdn.com/5.9.1/bundle.min.js
https://btphan95.github.io/
https://bugs.chromium.org/p/chromium/issues/detail?id=1065323
https://burnjet.com/
https://bycharlotte.com.au/
https://candidchronicle.com/
https://carlosvmpe.github.io/portafolio-angular/#/home
https://cdnportable.com/
https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setSkipAllPauses
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2366297
https://codereview.chromium.org/2615083002
https://csc.edu.vn/thiet-ke-website#chuyen-de3~chuyen-vien-thiet-ke-do-hoa-web-131
https://css-blocks.com/
https://dailyoffice.app/
https://damettoluca.com/
https://dandfplumbing.com/
https://daringfireball.net/projects/markdown/
https://data-11fec.firebaseapp.com/
https://dealsfinders.blog/
https://deardiary.wtf/
https://deb.nodesource.com/setup_14.x
https://designrevision.com/demo/shards-dashboards/index.html
https://dev.dlzpgroup.com/
https://devclub-kisii.firebaseapp.com/
https://developers.google.com/machine-learning/glossary/#c
https://development.talbots.com/on/demandware.store/Sites-talbotsus-Site
https://dijitul.uk/
https://dinnerbooking.com/dk/en-US/p/press
https://driivz.com/
https://drm39.ru/spec/tunisia/Kaliningrad/april/?early
https://eip.ceh.ac.uk/hydrology/water-resources/
https://elgentos.nl/
https://embeddedt.github.io/BucketGame/
https://eracreditservices.com/
https://erfolg-c.ru/
https://exablaze.com/
https://example.com/
https://fall-arrest.com/
https://fire.honeywell.com/#/overview/dashboard
https://free.test.io/?_ga=2.259134990.589578322.1555874257-2086775186.1555874257
https://ftnnews.com/
https://gathern.co/
https://gatsby-starter-hero-blog.greglobinski.com/
https://geoknigi.com/
https://ggstudyabroad.com/
https://giktar.ru/
https://goaccess.io/download
https://gohealthline.com/
https://gohealthline.com/32-foods-that-burn-belly-fat-fast/
https://golftocs.com/
https://googlechrome.github.io/devtools-samples/debug-js/get-started
https://handyytest.bar-at.in/
https://hogventure.com/
https://hub.docker.com/r/femtopixel/google-lighthouse
https://icommuse.com/ctcaelite/5/
https://icommuse.com/ctcaelite/5/#/tab/home
https://images-eu.ssl-images-amazon.com/images/G/01/AUIClients/ClientSideMetricsAUIJavascript@jserrorsForester.10f2559e93ec589d92509318a7e2acbac74c343a._V2_.js
https://indonesian-online.com/
https://ismaeljdz7.com/
https://jamstack.wtf/
https://jimgerland.com/
https://jionews.com/
https://joeybabcock.me/blog/
https://josephakayesi.com/
https://jsbin.com/
https://keralabookstore.com/new-books.do
https://kukadi.newsoftprojects.com/index.php
https://kumbier.it/
https://learn.javascript.ru/
https://learn.simbibot.com/
https://learning-templates.com/
https://lifetoolsdigital.com/5days/
https://lonelycpp.github.io/
https://lp.the123.co.il/sp/licoplus123/
https://m-g-shahriar.github.io/portfolio/
https://m.douban.com/
https://m.media-amazon.com/images/G/01/csm/showads.v2.js
https://m.mishifeng.com/city
https://mapy.cz/zakladni?x=14.4007705&y=50.0713520&z=11
https://marcoc76.github.io/calificaciones/
https://marriedgames.com.br/
https://mecasualty.com/
https://mentors.codingcoach.io/?language=html
https://minigames.mail.ru/biljard_devyatka
https://mnlegal.net/
https://mp.weixin.qq.com/s?__biz=MjM5MjAxNDM4MA==&mid=414293326&idx=1&sn=3d95dfb8e6bc4219a5714fbce89a8fc4&mpshare=1&scene=23&srcid=02245KJvVrwF3BVaUjhBMx9r#rd
https://mp.weixin.qq.com/s/L1xHLd-gKDsmi0lnSmm6pQ
https://mru.org/
https://myjoshem.github.io/assignments/weathersite/gallery.html
https://myw.natiki.net.au/
https://netk5.com.cn/
https://newspakistan.tv/
https://nicholasbering.ca/tools/2016/10/09/devtools-disable-caching/
https://nicholasireland.ca/
https://nigel-aves-photography.com/
https://nmsnewhaven.org/
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode
https://nutrifacts-app.firebaseapp.com/search
https://oautah.org/
https://ocioalicante.net/
https://oodle-demo.firebaseapp.com/#/
https://osteklenie812.ru/blog/moskitnie-setki-okna
https://password-generator.kamilnowak.com/
https://pdfbooksfree.pk/
https://pedrosa-andre.github.io/assignments/templesite/home.html
https://phaser-planes.glitch.me/
https://physicaltherapyweb.com/
https://piao.fr/2019/04/tatoueur-de-talent-le-travail-de-pierre-nous-a-bluffe/
https://poly.nomial.co.uk/
https://praveenpal4232.github.io/
https://preactjs.com/
https://prepaidcompare.net/
https://punyachatterjee.com/
https://pushdemo-f7986.firebaseapp.com/selfietravel/login
https://rachio.com/
https://rburkitt.github.io/BlazorApplication2/
https://renato66.github.io/
https://reviewsinscope.com/
https://rightwords.ro/
https://sa2019.siggraph.org/
https://sanjaytandon.in/
https://shivam-verma9999.github.io/sliding-tiles-puzzle/
https://shodipoayomide.com/
https://simplybearings.co.uk/shop/advanced_search_result.php?search_in_description=1&keywords=0.75X1.25X0.25_R23&search_inactive=on
https://sites.google.com/view/education-inc/home
https://smartfinancial.com/
https://sproboticworks.com/user/home
https://stackexchange.com/
https://stackoverflow.com/questions/18455644/programmatically-get-memory-usage-in-chrome
https://stackoverflow.com/questions/37494330/display-none-in-a-for-loop-and-its-affect-on-reflow
https://stackoverflow.com/questions/tagged/node.js
https://staging.digitary.net/
https://staging.suttacentral.net/
https://static.fsf.org/fsforg/rss/blogs.xml
https://stylesnbags.com/
https://surge.sh/
https://suzaanlainglaw.com/
https://t.ayaya.id/#/home
https://taslim.me/
https://template-page.firebaseapp.com/
https://testpwa-8ea96.firebaseapp.com/
https://thanosjs.org/?fbclid=IwAR16WOtqUeVaVeyDa-FZ3Q1aK-Q-2lWjYQcwx7gyVjkq75SG6Nv553NK1C0
https://therapyplayground.com/
https://timesheets.esyasoft.com/
https://timlive.tim.com.br/
https://trello.com/b/yl0WWJQN/srs
https://trenton-telge.github.io/MediView/
https://unitedbyblue.com/
https://unleashed-design.de/#/
https://upcreativ.com/
https://vehigrupo.com/
https://vladipur.by/pur-klej-dlya-proizvodstva-pokrytij-iz-rezinovoj-kroshki/
https://vue-agric.firebaseapp.com/
https://watch.sling.com/watch?channelId=261371704fd24f8fb9f29e483ba45062
https://wcmountainrealty.com/default.asp?content=expanded&search_content=results&this_format=1&mls_number=26011412&page=1&query_id=182715670&sortby=1
https://web.gencat.cat/ca/inici/
https://wfuneradoc-1.web.app/index.html
https://wiki.rookie-inc.com/serverapps/security/ssh
https://wildhunt.org/
https://womantalk.com/
https://wwos.nine.com.au/motorsport/live-scores/motogp-circuit-of-the-americas-2019/motogp-3-2019-0
https://www.aciaalfenas.com.br/home
https://www.airbnb.com.br/
https://www.alexandersparks.com/
https://www.amazon.com/
https://www.amazon.fr/
https://www.anthem.com/
https://www.apostillecanada.org/
https://www.artistictile.com/
https://www.asaudeonline.com.br/
https://www.ashware.nl/
https://www.atlantisbahamas.com/
https://www.avalara.com/us/en/index.html
https://www.awwwards.com/
https://www.backmeup.co.uk/
https://www.bandlab.com/mix-editor
https://www.berfect.de/
https://www.bigbreaks.com/
https://www.bio-rad-antibodies.com/
https://www.blbrokers.com/
https://www.bmu.edu.in/
https://www.boticario.com.br/
https://www.broadcom.com/
https://www.chetu.com/
https://www.chromatix.com.au/
https://www.chronoshop2shop.fr/fr
https://www.clouty.ru/
https://www.clublr.gr/
https://www.consumerfinance.gov/about-us/blog/economic-impact-payment-prepaid-card/
https://www.cort.com/
https://www.countystonegranite.co.uk/
https://www.cybermiles.io/en-us/
https://www.damacproperties.com/
https://www.deakin.edu.au/
https://www.dejongintra.nl/
https://www.deque.com/axe/
https://www.derby.ac.uk/
https://www.donatekart.com/
https://www.drlucianopellegrino.com.br/
https://www.e2language.com/
https://www.ebay.com/
https://www.ecoconcepts.co/
https://www.edgeclothing.com.au/collections/womens-pants
https://www.elitesingles.com/
https://www.eq-love.com/fr/
https://www.eyebuydirect.com/eyeglasses/women
https://www.fashionworld.co.uk/
https://www.flipkart.com/
https://www.floweraura.com/
https://www.freehosting.com/tos.html
https://www.freizi.at/
https://www.frioval.cl/
https://www.ft.com/
https://www.gemini-us.com/
https://www.glosarioit.com/
https://www.goldenplanet.dk/
https://www.google.es/
https://www.graphitas.co.uk/
https://www.gundtoft.dk/
https://www.gupshup.io/developer/docs/bot-platform/guide/intro-to-gupshup-bot-builder
https://www.guthriebowron.co.nz/
https://www.hamilecarsi.com/
https://www.hastayataklari.co/
https://www.holidify.com/places/tehri-garhwal/photos.html
https://www.htmracing.it/
https://www.iiad.edu.in/
https://www.indiatvnews.com/elections
https://www.iontocentre.com/
https://www.itriangle.in/
https://www.jasta5.org/
https://www.jonniegrieve.co.uk/
https://www.joseluisandrade.com/
https://www.jungelinke.at/
https://www.justeat.it/
https://www.kenamobile.it/
https://www.kentuckymathematics.org/
https://www.kidsgo.de/
https://www.kitchenaid.com.co/ksm150psmy/p
https://www.kttape.com/
https://www.kyrillrapp.com/
https://www.logycacolabora.com/
https://www.makello.com/
https://www.mediaplayer10.com/
https://www.meetmatch.biz/
https://www.mudanzasmitre.com/
https://www.mysense.com.my/
https://www.naqshi.com/
https://www.news18.com/
https://www.noom.com/#/
https://www.npmjs.com/package/which
https://www.nsowo.com/16624/%d8%a3%d9%81%d8%b6%d9%84-%d9%88%d8%b8%d8%a7%d8%a6%d9%81-%d9%81%d9%8a-%d8%a7%d9%84%d8%b9%d8%a7%d9%84%d9%85-%d9%88%d8%a7%d9%84%d8%a3%d8%b9%d9%84%d9%89-%d8%b1%d8%a7%d8%aa%d8%a8%d8%a7/
https://www.nsowo.com/30876/%D8%A3%D8%B3%D9%85%D8%A7%D8%A1-%D8%A8%D9%86%D8%A7%D8%AA-%D9%85%D8%B9-%D8%A7%D9%84%D8%B5%D9%81%D8%A7%D8%AA-%D9%84%D9%83%D9%84-%D8%A7%D8%B3%D9%85-%D9%81%D8%AA%D8%A7%D8%A9/
https://www.officedepot.com/configurator/create-on-demand/#/product/poster/1041
https://www.olx.in/
https://www.openstudio.one/
https://www.origin.io/
https://www.ourkyj.com/#/
https://www.phixer.net/
https://www.pioneerbricks.com/
https://www.pioneerelectronics.com/PUSA/Car/DVD+Receivers
https://www.pragtech.co.in/
https://www.psm.org.ph/guides-notes-faqs/
https://www.redfin.com/NY/Deer-Park/214-Old-Country-Rd-11729/home/21430946
https://www.reesby.com.au/
https://www.resultadofacil.com.br/
https://www.saatchiart.com/artadvisory
https://www.sce.com/
https://www.sdsgroup.ro/
https://www.sellsa.co.za/
https://www.sitespeed.io/
https://www.solactive.com/
https://www.stenaline.se/till-danmark
https://www.stylecraze.com/articles/eyelash-extensions-guide/
https://www.tekscan.com/
https://www.tiffany.com/
https://www.tpkha.com/
https://www.trekksoft.com/
https://www.tributemedia.com/
https://www.uncappedfibre.co.za/telkom/openserve?fbclid=IwAR3mmZzaalR7eWrObcYi3LAagagaocBzroJdAj0DYe4AVwkci0EjdtLnwl4
https://www.verivox.de/
https://www.vsointernational.org/
https://www.w3schools.com/
https://www.wannaexpresso.com/2021/02/19/m1-macbook-rbenv/
https://www.wannaexpresso.com/2021/02/20/m1-macbook-minecraft/
https://www.wikimass.com/c/biggest-of-three-numbers
https://www.woolaroc.org/become-a-member
https://www.worldrace.org/
https://www.yardhopping.com/
https://www.zenlayer.com/#
https://x2pos.com/
https://xpos-master.firebaseapp.com/portal
https://yabbermarketing.com/
https://yhotie.com/
https://zoihospitals.com/
`.trim().split('\n').slice(0, 10);

const sha = execFileSync('git', ['rev-parse', 'HEAD']).toString().trim();
const name = `baseline-${sha}`;
const iter = 1;

execFileSync('node', [
    'core/scripts/compare-runs.js',
    '--name', name,
    '--collect',
    '-n', String(iter),
    `--lh-flags='--chrome-flags=--headless=new'`,
    '--urls', ...urls,
], {stdio: 'inherit'});

const dataDir = `timings-data/${name}`;
let timeouts = 0;
for (const lhrPath of glob.sync(`${dataDir}/**/lhr-*.json`)) {
    const lhr = JSON.parse(fs.readFileSync(lhrPath, 'utf-8'));
    console.log(lhr.runWarnings, lhr.runtimeError);
    if (true) {
        timeouts += 1;
    }
}

fs.writeFileSync(`${dataDir}/result.txt`, JSON.stringify({timeouts}));
